{% set name = "colormaps" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c703d62a4fededfcfed57bef6aa772422b535896645cbf8c58690e4bbe16005c

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - colormaps
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
about:
  home: "https://pratiman-91.github.io/colormaps/"
  license: MIT
  license_family: MIT
  license_file: "LICENSE"
  summary: "Collection of colormaps or color palettes for Python"
  doc_url: "https://pratiman-91.github.io/colormaps/"
  dev_url: "https://github.com/pratiman-91/colormaps"

extra:
  recipe-maintainers:
    - pratiman-91
